<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hide-Optional-Fields</name>
   <tag></tag>
   <elementGuidId>7fa68cfe-4cac-422b-8372-56e140aaaf29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/section/div/div/div[2]/div/div[2]/div/div[2]/div/div/div[1]/div[1]/div/div/div[1]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
